name: Secret Detection

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  secret-scan:
    uses: NifasatBeg/CashFlowDeps/.github/workflows/secret-scan.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}